//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem
{


    public partial class WebForm2
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
<<<<<<<< HEAD:homepage_code.aspx.designer.cs
        /// test control.
========
        /// Image1 control.
>>>>>>>> 93b916375e8ff24e61900e7ba6c8798fd1c35d83:AboutUs.aspx.designer.cs
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<<< HEAD:homepage_code.aspx.designer.cs
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl test;
========
        protected global::System.Web.UI.WebControls.Image Image1;

        /// <summary>
        /// Label1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label1;
>>>>>>>> 93b916375e8ff24e61900e7ba6c8798fd1c35d83:AboutUs.aspx.designer.cs
    }
}
